### PR TITLE
code quality, typechecking, linting, formatting

### PR DESCRIPTION
**Pull request by dni**
- formatting
- add linting to extensions

### CODE REVIEW

**Comment by bitkarrot** [comment]
wen merge? 🥇 :D

**Comment by dni** [comment]
i am not 100% happy with that approach yet. needs some more thinking

**Comment by bitkarrot** [comment]
@dni i'm working on a new extension and i want to 'use the tools', should i just copy your branch for now and then update it later? I presume we still will use black, mypy etc linting

**Comment by dni** [comment]
yeah, try it, its a good start but it still is more of a draft / vague guideline, but i guess you can always change it later aswell.

**Comment by dni** [comment]
https://github.com/lnbits/example/pull/9

**Pull request closed without merging**
